# Colores base
BG_PRIMARY      = "#08110F"
BG_SECONDARY    = "#142323"
ACCENT_GREEN    = "#619184"
ACCENT_ORANGE   = "#E37451"
ACCENT_YELLOW   = "#E6C99F"
TEXT_PRIMARY    = "#f5f1da"
TEXT_SECONDARY  = "#C0BCA2"
ACCENT_RED      = "#E44D3C"

# Semántica financiera
COLOR_INGRESO   = ACCENT_GREEN
COLOR_GASTO     = ACCENT_ORANGE
COLOR_ALERTA    = ACCENT_RED
COLOR_NEUTRO    = ACCENT_YELLOW

# Tipografía
FONT_SIZE_SM    = 12
FONT_SIZE_MD    = 16
FONT_SIZE_LG    = 20
FONT_SIZE_XL    = 28

# Espaciado y bordes
BORDER_RADIUS   = 12
PADDING_SM      = 8
PADDING_MD      = 16
PADDING_LG      = 24